log_level: "INFO"

# config.yaml
training:
  num_epochs: 25
  lr: 0.0002
  val_interval: 2
  seed: 42
  run_name: "Final_F96_H192_E25"
  save_dir: "./best_models"
  device: null
  kl_annealing: true
  optimizer:
    name: adamw
    weight_decay: 0.0001
  scheduler:
    name: cosine_step

model:
  num_latent: 158
  num_portfolio: 128
  num_factor: 96
  hidden_size: 192

data:
  dataset: "CN"
  seq_len: 20
  num_workers: 2
  fit_start_time: "2009-01-01"
  fit_end_time: "2017-12-31"
  val_start_time: "2018-01-01"
  val_end_time: "2018-12-31"
  test_start_time: "2019-01-01"
  test_end_time: "2020-12-31"
  select_feature: null

mlflow:
  experiment: "FactorVAE"
  tracking_uri: "sqlite:///model_tracking/mlflow.db"


test:
  model_dir: "./best_models"
  model_name: "Final_F96_H192_E25_factor_96_hdn_192_port_128_seed_42.pt" 

# Optional: Add overrides for different environments (e.g., dev/prod)
# dev:
#   training:
#     num_epochs: 1




